### ISSUE TITLE
División y filtrado

### ISSUE THREAD

**Issue by sur6i6orX** [Karmaz95/crimson_cracking#1]
Hola en primer lugar Gracias por esta inmensa aportación y quería decirles Cómo es que hago para poder filtrar el txt ya que aveces solo se necesita aquéllas líneas con 8 caracteres o más así pues las líneas que contienen menor a 8 gastarian la cpu podría alguien explicar como es que lo filtro ya lo intente pero como es muy grande para abrirlo con el block de notas se me cuelga o me sale errorMemmory

**Comment by Karmaz95** [comment]
You can use the `grep` or `awk` command. 
I described it in [HOW TO USE](https://github.com/Karmaz95/crimson_cracking?tab=readme-ov-file#how-to-use).

For example, extracting passwords containing 8 or more characters but less or equal than 12:
```
awk 'length >= 8 && length <= 12' crimson_cracking.txt > crack.txt
```
